### PR TITLE
access protocols deprecated

### PR DESCRIPTION
**Pull request by sdancer**
delete the access protocol so it can compile in elixir 1.3

### CODE REVIEW

**Comment by krystianity** [comment]
+++

**Comment by SKoschnicke** [comment]
Would be cool if you could merge this @meh. Without it, the urna and cauldron libraries can't be compiled anymore (on elixir 1.4). I'm happy to help, too.

**Comment by meh** [comment]
I have no idea why I didn't merge it, notifications lost to the times I say.

**Comment by SKoschnicke** [comment]
Well, that was fast, thanks! Could you put updated library versions on hex, too?

**Comment by meh** [comment]
Yeah, I'm fixing up warnings and whatnot first.

**Pull request merged**
